name: ci

on:
  pull_request:
  push:
    branches:
      - local_testing
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        if: startsWith(github.ref, 'refs/tags/')
        run: docker login -u abhay900 -p abhay12
      - name: build-publish-image                  
        id: docker_build 
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./benchmarks/Dockerfile
          platforms: linux/arm64,linux/amd64 
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: datadog/dd-trace-py:latest
 
